### ISSUE TITLE
Missing dependencies like: com.lmco.efoss.sbom:sbom-commons

### ISSUE THREAD

**Issue by michalmartys** [CycloneDX/sbom-combiner#3]
Could not resolve dependencies for project com.lmco.efoss:sbomcomparator:jar:1.2.1: Failure to find com.lmco.efoss.sbom:sbom-commons:jar:1.1.1 in https://repo.maven.apache.org/maven2 was cached in the local repository

Actually, I have no idea where can I find com.lmco.efoss.sbom:sbom-commons:jar:1.1.1 (missing in the Central Repos)

**Comment by acdop100** [comment]
This can be fixed manually:

1. Clone this repo.
2. Clone https://github.com/CycloneDX/sbom-commons
3. In the sbom-commons repo, run `mvn clean package`
4. Take the resulting .jar file and place it in sbom-combiner/src/main/resources. You'll need to make the resources folder yourself
5. Find and replace all occurances of `com.lmco.efoss.sbom.commons` with `org.cyclonedx.contrib.com.lmco.efoss.sbom.commons`. Really easy with VSCode.
6. You may need to do the above for some other imports as well. It's not hard.
7. Change the sbom-commons dependency in pom.xml to this:
```
                <dependency>
			<groupId>org.cyclonedx.contrib.com.lmco.efoss.sbom.commons</groupId>
			<artifactId>sbom-commons</artifactId>
			<version><SBOM_COMMON_VERSIONS></version>
			<scope>system</scope>
    		<systemPath>${project.basedir}/src/main/resources/<NAME_OF_COMMON_JAR>.jar</systemPath>
		</dependency>
```
8. Run `mvn clean package` in this repo and you should be able to build the package.

**Comment by michalmartys** [comment]
Of course, can build it locally and provide e.g. as <systemPath> since the sbom-commons project is also available in GitHub. Thanks for your help.
